// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8D58sCkydSEhzCUY7P8mWcF2ufYU7rT0',
    appId: '1:1033375049723:web:f288ca68cf4fdd4b658d5e',
    messagingSenderId: '1033375049723',
    projectId: 'flutterchatpro-1124c',
    authDomain: 'flutterchatpro-1124c.firebaseapp.com',
    storageBucket: 'flutterchatpro-1124c.firebasestorage.app',
    measurementId: 'G-MS6E757N1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfY-ybF9QfpZaBBX77qOxHoZzIPtm884',
    appId: '1:1033375049723:android:8ddb902637a2f095658d5e',
    messagingSenderId: '1033375049723',
    projectId: 'flutterchatpro-1124c',
    storageBucket: 'flutterchatpro-1124c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmS7QaVkxjlEDzU6iTSHfNi_U9AdSs5o8',
    appId: '1:1033375049723:ios:a711494adda928f7658d5e',
    messagingSenderId: '1033375049723',
    projectId: 'flutterchatpro-1124c',
    storageBucket: 'flutterchatpro-1124c.firebasestorage.app',
    iosBundleId: 'com.khoilt.flutterchatapp',
  );
}
